### ISSUE TITLE
Images loading slowly

### ISSUE THREAD

**Issue by EMTuckerLab** [globalbioticinteractions/ecm-workshop#1]
The images load pretty slowly, particularly on the {"Individual Data Transcriptions Worksheet activity" page](https://www.globalbioticinteractions.org/ecm-workshop/03-individual/index.html). 
Currently the images are linked to a depository on my imgur.com account because I could get the images to link/load properly within the github depository (https://github.com/globalbioticinteractions/ecm-workshop/tree/gh-pages/fig).
If you could figure out the proper code to link to the images in the github folder instead of imgur that would be great - especially if it makes things load faster. If the images are still slow to load after that, I can make them a smaller file size. 
Thanks!

**Comment by jhpoelen** [comment]
Image loading prior to optimization attempt on a wifi6 / 500Mb fiber internet connection running opera browser Version:60.0.3255.170

![Screenshot from 2022-06-18 07-54-02](https://user-images.githubusercontent.com/1084872/174438628-da8520ab-e4a2-4335-a798-275fe555e9f0.png)

**Comment by jhpoelen** [comment]
Attempting to make links relative, so they load via GitHub pages. . . testing. . .

**Comment by jhpoelen** [comment]
hey @EMTuckerLabUMMZ just attempted to make links relative (e.g., using ```../files/...``` and ```../fig/...``` links). Gotta run an errant, be back in early afternoon central. Will test some more later. Please don't worry about the links until I test them.

**Comment by EMTuckerLab** [comment]
Thanks Jorrit!!


----------
Erika Tucker
MPM | BON
Bug.News

**Comment by jhpoelen** [comment]
I tried to take a stab at the image, reducing them in size. I placed the original images in fig/orig . 

Also, please note I made a reusable "include" snippet at _include/logos.html and placed ```{% include logos.html %}``` in lesson footer and main index.md . Also, I attempted to make all img links relative using ```{{ site.baseurl }}/fig/[name of image]``` .

Please re-open issue or comment if you feel there's more work to do!
