### ISSUE TITLE
Larger font size? On all pages

### ISSUE THREAD

**Issue by EMTuckerLab** [globalbioticinteractions/ecm-workshop#2]
The font size for the main text on all pages of the website seems small (headers I think are probably fine). 
Can you look into a universal font size increase for the main text? Or an extra snippet of code that can easily be added to adjust it on each page...
Thanks!

**Comment by jhpoelen** [comment]
see before / after screenshots on increasing font-size from 14pt to 20pt . 

see https://github.com/globalbioticinteractions/ecm-workshop/commit/77931d6d67f4717f933039bf24b2cd214b847790 for the file that controls it.

before 
![Screenshot from 2022-06-17 22-44-18](https://user-images.githubusercontent.com/1084872/174421876-b0bb4769-19e6-4e59-b05a-8b756bad7f37.png)

after

![Screenshot from 2022-06-17 22-49-52](https://user-images.githubusercontent.com/1084872/174421911-3aacc943-f2f0-4372-ac26-9a85ba455e6f.png)

please re-open if you have remaining concerns about font-size. 

Thanks for documenting this!

**Comment by EMTuckerLab** [comment]
So much better! Thank you!!
