### ISSUE TITLE
Where is the footer file located?

### ISSUE THREAD

**Issue by EMTuckerLab** [globalbioticinteractions/ecm-workshop#3]
Can you help me find the location of the footer file for editing footer content?
Mostly I just want to add our logos to it. And maybe the TPT banner with lice all over it (same as on our ppt slides) it that doesn't look too busy...
I cannot find the correct file to edit/modify. 
Thanks!

**Comment by jhpoelen** [comment]
Please note that I added the logos to footer via ```_includes/lesson_footer.html``` using ```{% include logos.html %}```
