### ISSUE TITLE
Move keypoints box on lessons up a bit

### ISSUE THREAD

**Issue by EMTuckerLab** [globalbioticinteractions/ecm-workshop#4]
Low priority issue, but if possible:
Can we move the "key points" box on the lesson pages up a bit? So that it sits directly above the "What's next" section on each page, but below everything else. Currently, it is the very last thing before the footer which is ok, but I think it would be nice to have key points before people are tempted to click the link to the next lesson. 
Thanks!

**Comment by jhpoelen** [comment]
Haven't yet figured out a way to easily move the key points up.

If you don't think it is a big deal to keep it as is, I'd suggest to leave it for now, and close this issue.

**Comment by EMTuckerLab** [comment]
Not a big deal. I think we did great. Especially with the tight timeframe!
