### ISSUE TITLE
File with home page header?

### ISSUE THREAD

**Issue by EMTuckerLab** [globalbioticinteractions/ecm-workshop#6]
Ok, apparently I don't know where the file to edit the main header on the home page is either (I can edit the sub header in index file, but not the top larger header). 
We discussed changing "Species Interaction Data Workshop" to "Interaction Data Interpretation Workshop", but after searching through the files today and not finding the correct file - I'll open an issue. 

Please direct me to the correct file, or you can change if you want. Either way. 
Thanks!

**Comment by jhpoelen** [comment]
The title of the workshop can be found in ```_config.yml```. 

I've attempted to update the title to be ```Interaction Data Interpretation Workshop```.

**Comment by jhpoelen** [comment]
Title has been updated. See attached screenshot of https://www.globalbioticinteractions.org/ecm-workshop/ on 18 June 2022. 

![Screenshot from 2022-06-18 16-50-16](https://user-images.githubusercontent.com/1084872/174458015-835ba0ed-c669-4078-9836-91a511e6f034.png)
