### ISSUE TITLE
Remove "alpha version" banner?

### ISSUE THREAD

**Issue by EMTuckerLab** [globalbioticinteractions/ecm-workshop#8]
I think the webpage is pretty much as done as it will be... I think we got this together amazingly quickly :)
The only thing that didn't get modified is the FAQ page, but at the moment I'm drawing a blank on what should go there. Maybe I'll make and issue for that...

So - can we remove the banner on all the lesson pages? The one that says: "This lesson is in the early stages of development (Alpha version)" 
I'm not sure how to do that...

Thanks!

**Comment by jhpoelen** [comment]
@EMTuckerLabUMMZ thanks for sharing! 

I've updated the lifecycle from alpha to stable. Please confirm by closing the issue.

**Comment by EMTuckerLab** [comment]
Thanks!
